### ISSUE TITLE
Missing some Dlls

### ISSUE THREAD

**Issue by thumarbhavesh10** [OpenChargingCloud/WWCP_OCPP#2]
Can you please provide missing dlls as per attached screenshots

![image](https://user-images.githubusercontent.com/5073335/84296503-b97b4200-ab69-11ea-879d-72835620585c.png)

**Comment by ahzf** [comment]
Sorry, this repository is a bit out-of-date. We will update it with a rewritten version of this OCPP library within the next weeks.

**Comment by thumarbhavesh10** [comment]
Hi @ahzf 

I have checked recently with this code but still some DLLs are missing.
